name: Minify JS

on:
  push:
    paths:
      - 'draw.js'

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
  # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
     - uses: actions/checkout@v2

     - name: Auto Minify
       uses: nizarmah/auto-minify@v2.1
       
     - name: Remove characters and create draw.load.js
       run: |
         content="$(cat draw.min.js)"   
         modified_content="\${content:23:-5}"
         echo "$modified_content" > draw.load.js
       shell: bash
       
     
  # Auto commits minified files to the repository
  # Ignore it if you don't want to commit the files to the repository 
     - name: Auto committing minified files
       uses: stefanzweifel/git-auto-commit-action@v4
       with:
           commit_message: "Github Action: Auto Minified JS files"
           branch: ${{ github.ref }}
