name: Minify JS

on:
  push:
    paths:
      - 'draw.js'

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          files: 'draw.js'
          output: '.'

      - name: Rename minified file
        run: mv draw.min.js draw-min.js

      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "GitHub Action: Auto Minified draw.js"
          branch: ${{ github.ref }}
